function seRompe(){
    return 3 + z
}
try{
    seRompe()
}
catch(err){
    console.log('ha habido un error')
}
console.log('aca continua')

